### ISSUE TITLE
CI build framework for ebash

### ISSUE THREAD

**Issue by marshallmcmullen** [marshallmcmullen/ebash#8]
ebash used to be built and tested extensively in-house but now that it's been open sourced we need to replace that framework with a cloud-based CI/CD framework. When I first did this I ported it over to Travis CI. However, that had a number of limitations including time limits on test runs and inability to run inside extensive set of Linux distros. I think that the built-in "Actions" framework inside GitHub will suite my needs better. It does not have the time limits that Travis CI does, and has a rich framework for running all jobs in parallel across a matrix of Linux containers.

**Comment by marshallmcmullen** [comment]
Prototype working across all supported OS and Distros:

https://github.com/marshallmcmullen/ebash/actions/runs/364808074

**Comment by marshallmcmullen** [comment]
Still have a few test failures to sort through on Alpine, but otherwise looking very promising.

**Comment by cseelye** [comment]
Very cool

**Comment by marshallmcmullen** [comment]
> Very cool

Oh Hey @cseelye !! Glad you like it. I'm getting to use ebash a lot at my new job so I wanted to setup a good framework for test and validation to build on :-)
