### ISSUE TITLE
Create ebash Issues

### ISSUE THREAD

**Issue by marshallmcmullen** [marshallmcmullen/ebash#9]
This is an open invite to those that I know use ebash (a.k.a. `bashutils`) to please open issues for any bugs or feature requests you have for ebash. I am getting to use ebash at my new job rather extensively so I want to make sure any known issues are addressed and resolved ASAP.

@michael-odell 
@ericpe 
@cseelye 
@tjdistler 

I don't have github names for Brendan or James, but please share this with them if you don't mind. And anyone else that may care. Thanks guys!!

**Comment by ericpe** [comment]
Brendon is @sargasso
Martin is @mekuchta

**Comment by ericpe** [comment]
James is @jwkblades

**Comment by marshallmcmullen** [comment]
Thanks so much @ericpe .

**Comment by marshallmcmullen** [comment]
Now that everyone I wanted to get notified has been notified I'm going to close this issue. Folks, feel free to create issues for anything you want fixed or improved.
